# 
# PROJECT FILE generated by "Pelles C for Windows, version 8.00".
# WARNING! DO NOT EDIT THIS FILE.
# 

POC_PROJECT_VERSION = 7.00#
POC_PROJECT_TYPE = 11# POC_PROJECT_OUTPUTDIR = output#
POC_PROJECT_RESULTDIR = .#
POC_PROJECT_ARGUMENTS = #
POC_PROJECT_ZIPEXTRA = #
CC = pocc.exe#
AS = poasm.exe#
RC = porc.exe#
LINK = polink.exe#
SIGN = posign.exe#
CCFLAGS = -Tamd64-coff -Ot -W1 -Ze -std:C11#
ASFLAGS = -AAMD64#
RCFLAGS = -r#
#LINKFLAGS = -machine:amd64 -subsystem:windows kernel32.lib user32.lib gdi32.lib comctl32.lib comdlg32.lib advapi32.lib delayimp64.lib -dll#
LINKFLAGS = -machine:amd64 -subsystem:console kernel32.lib user32.lib gdi32.lib comctl32.lib comdlg32.lib advapi32.lib delayimp64.lib#
SIGNFLAGS = -location:CU -store:MY -timeurl:http://timestamp.verisign.com/scripts/timstamp.dll -errkill#
INCLUDE = f:\PellesC\Include\Win;f:\PellesC\Include;f:\CUnit\Include#
LIB = f:\PellesC\Lib\Win64;f:\PellesC\Lib;f:\CUnit#
MYDEFS = #-DTEST_ALLOC#

INCDIR = /I"f:\PellesC\Include\Win" \
	/I"f:\PellesC\Include"\
	/I"f:\CUnit\include"

LIBDIR = /LIBPATH:"f:\PellesC\Lib\Win64" \
	/LIBPATH:"f:\PellesC\Lib" \
	/LIBPATH:"f:\CUnit"

# Build and run the test suite
test: output\test.exe
	output\test.exe

output\test.exe: \
	output\obj\alloc.obj \
	output\obj\winpath.obj \
	output\obj\utf8.obj \
	output\obj\xprintf.obj \
	output\obj\winpath_suite.obj \
	output\obj\alloc_suite.obj \
	output\obj\utf8_suite.obj \
	output\obj\printf_suite.obj \
	output\obj\shf.obj \
	output\obj\test_main.obj
	$(LINK) $(LIBDIR) $(LINKFLAGS) cunit.lib -out:"$@" $**

alloc_test.exe: \
	output\obj\alloc.obj
	$(LINK) $(LIBDIR) $(LINKFLAGS) -out:"$@" $**
# 
# Build alloc.obj.
# 
output\obj\alloc.obj: \
	alloc.c
	$(CC) $(INCDIR) $(CCFLAGS) $(MYDEFS) /c "$!" -Fo"$@"

output\obj\shf.obj: \
	shf.c
	$(CC) $(INCDIR) $(CCFLAGS) $(MYDEFS) /c "$!" -Fo"$@"

output\obj\winpath.obj: \
	winpath.c
	$(CC) $(INCDIR) $(CCFLAGS) $(MYDEFS) /c "$!" -Fo"$@"

output\obj\utf8.obj: \
	utf8.c
	$(CC) $(INCDIR) $(CCFLAGS) $(MYDEFS) /c "$!" -Fo"$@"

output\obj\xprintf.obj: \
	printf\xprintf.c
	$(CC) $(INCDIR) $(CCFLAGS) $(MYDEFS) /c "$!" -Fo"$@"

#
# Build tests
# 
output\obj\printf_suite.obj: \
	tests\printf_suite.c
	$(CC) $(INCDIR) $(CCFLAGS) $(MYDEFS) /c "$!" -Fo"$@"

output\obj\write_file_suite.obj: \
	tests\write_file.c
	$(CC) $(INCDIR) $(CCFLAGS) $(MYDEFS) /c "$!" -Fo"$@"

output\obj\utf8_suite.obj: \
	tests\utf8_suite.c
	$(CC) $(INCDIR) $(CCFLAGS) $(MYDEFS) /c "$!" -Fo"$@"

output\obj\winpath_suite.obj: \
	tests\winpath_suite.c
	$(CC) $(INCDIR) $(CCFLAGS) $(MYDEFS) /c "$!" -Fo"$@"

output\obj\alloc_suite.obj: \
	tests\alloc_suite.c
	$(CC) $(INCDIR) $(CCFLAGS) $(MYDEFS) /c "$!" -Fo"$@"

output\obj\test_main.obj: \
	tests\test_main.c
	$(CC) $(INCDIR) $(CCFLAGS) $(MYDEFS) /c "$!" -Fo"$@"

clean: 
	del output\obj\*.obj 
	del output\*.exe 

#.SILENT:
